### PR TITLE
[FIX] Include module name in log for duplicate module declaration

### LINKED ISSUE #186: Name of module with problem missing from "duplicate declaration of module name" warning
## Expected Behavior
"duplicate declaration of module name at" build warning message should have the offending module name.

## Current Behavior
"duplicate declaration of module name at" build warning message does not show the module name.  The message just ends after the word "at".

## Steps to reproduce the issue
1. In the openui5-sample-app project, npm install the dependencies.
2. Open up node_modules/@openui5/sap.m/src/sap/m/Button.js.
3. Add a `jQuery.sap.declare("sap.m.Button");` line inside of the AMD-style sap.ui.define function to trigger the build warning.
4. Run `ui5 build self-contained`
5. Notice the "WARN lbt:analyzer:JSModuleAnalyzer duplicate declaration of module name at" message in the output.

## Context
- UI5 Module Version *(output of `ui5 --version` when using the CLI)*: `1.2.0`
- Node.js Version: `v10.14.1`
- npm Version: `6.7.0`
- OS/Platform: `Windows 10`
- Browser *(if relevant)*: `N/A`
- Other information: ``

## Affected components *(if known)*

- [X] [ui5-builder](https://github.com/SAP/ui5-builder)
- [ ] [ui5-server](https://github.com/SAP/ui5-server)
- [ ] [ui5-cli](https://github.com/SAP/ui5-cli)
- [ ] [ui5-fs](https://github.com/SAP/ui5-fs)
- [ ] [ui5-project](https://github.com/SAP/ui5-project)
- [ ] [ui5-logger](https://github.com/SAP/ui5-logger)

## Log Output / Stack Trace
```
$ ui5 build self-contained
INFO: Using local @ui5/cli installation

info builder:builder Building project openui5-sample-app not including dependencies...
info builder:builder 🛠  (1/1) Building project openui5-sample-app
info builder:builder application openui5-sample-app 🔨 (1/8) Running task replaceCopyright...
info builder:builder application openui5-sample-app 🔨 (2/8) Running task replaceVersion...
info builder:builder application openui5-sample-app 🔨 (3/8) Running task generateFlexChangesBundle...
info builder:builder application openui5-sample-app 🔨 (4/8) Running task generateStandaloneAppBundle...
ERR! lbt:bundle:Resolver **** error: missing module sap/ui/support/Bootstrap.js, required by sap/ui/core/Core.js
WARN lbt:analyzer:JSModuleAnalyzer duplicate declaration of module name at
info builder:builder application openui5-sample-app 🔨 (5/8) Running task transformBootstrapHtml...
info builder:builder application openui5-sample-app 🔨 (6/8) Running task createDebugFiles...
info builder:builder application openui5-sample-app 🔨 (7/8) Running task uglify...
info builder:builder application openui5-sample-app 🔨 (8/8) Running task generateVersionInfo...
info builder:builder Build succeeded in 6.45 s

```

### PR DESCRIPTION
**Pull request by tommyvinhlam**
Fixes #186

### CODE REVIEW

File: lib/lbt/analyzer/JSModuleAnalyzer.js [hunk 1]
```diff
@@ -398,7 +398,7 @@ class JSModuleAnalyzer {
 					 */
 				} else if ( nModuleDeclarations > 1 && name === info.name ) {
 					// ignore duplicate declarations (e.g. in behavior file of design time controls)
-					log.warn("duplicate declaration of module name at %s", getLocation(args));
+					log.warn("duplicate declaration of module "+ `${getLocation(args)}`+ " in "+ `${name}`);
```
Comment (codeworrior) [inline lib/lbt/analyzer/JSModuleAnalyzer.js]: When you start using es6 string templates, why don't you make the whole line a single template?

  `duplicate declaration of module ${getLocation(args)} in ${name}`

Comment (tommyvinhlam) [reply lib/lbt/analyzer/JSModuleAnalyzer.js]: So true...
